REM %1 clean -i github.com/TWINGSISTER/machine/...
REM %1 install -v -gcflags "-N -l" github.com/TWINGSISTER/machine/...
%1 clean -i github.com/TWINGSISTER/docker-machine-driver-qemu-windows/...
%1 install -v -gcflags "-N -l" github.com/TWINGSISTER/docker-machine-driver-qemu-windows/...
%1 build  -v -gcflags "-N -l" -o Z:\docker-toolbox-portable-win32-18.09.1-7\app\docker-machine-driver-qemu.exe github.com/TWINGSISTER/docker-machine-driver-qemu-windows/src/windriver/cmd/main.go